# Generated by Django 5.1.2 on 2025-02-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='svg_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
