# Generated by Django 5.1.2 on 2025-02-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userlevel_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('travelers', models.IntegerField(default=1)),
            ],
        ),
    ]
