# Generated by Django 5.1.2 on 2025-02-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
