# Generated by Django 5.1.2 on 2025-02-22 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_ride_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arriving_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ride',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
