# Generated by Django 5.1.2 on 2025-02-22 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_ride_arriving_date_ride_created_on_ride_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRideAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_driver', models.BooleanField(default=False)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='base.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Ride Association',
                'verbose_name_plural': 'User Ride Associations',
                'unique_together': {('user', 'ride')},
            },
        ),
    ]
