# Generated by Django 5.1.2 on 2025-02-22 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userrideassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_place_id', models.CharField(max_length=255)),
                ('origin_latitude', models.FloatField()),
                ('origin_longitude', models.FloatField()),
                ('destination_place_id', models.CharField(max_length=255)),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('duration_text', models.CharField(max_length=100)),
                ('selected_route_index', models.IntegerField()),
                ('selected_route_polyline', models.TextField()),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_details', to='base.ride')),
            ],
        ),
    ]
