# Generated by Django 5.1.2 on 2025-02-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_routedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='destination_longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='destination_place_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='duration_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='origin_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='origin_longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='origin_place_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='selected_route_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='selected_route_polyline',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='RouteDetails',
        ),
    ]
