# Generated by Django 5.1.2 on 2025-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ride_destination_latitude_ride_destination_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number_user',
            field=models.TextField(blank=True, default='387603067074', null=True),
        ),
    ]
