# Generated by Django 5.1.2 on 2025-02-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_path_to_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='path_to_profile_picture',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
