# Generated by Django 5.1.2 on 2025-02-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_path_to_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='arriving_date',
        ),
    ]
