# Generated by Django 5.1.2 on 2025-02-22 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_ride_arriving_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ride Application',
                'verbose_name_plural': 'Ride Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'ride')},
            },
        ),
    ]
