# Generated by Django 5.1.2 on 2025-02-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='PREPARING', max_length=10),
        ),
    ]
