# Generated by Django 5.1.2 on 2025-02-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_ride_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlevel',
            options={'ordering': ['points']},
        ),
    ]
