# Generated by Django 5.1.2 on 2025-02-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_userlevel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='path_to_profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_description',
        ),
    ]
