# Generated by Django 5.1.2 on 2025-02-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='penguins_saved',
            field=models.IntegerField(default=0),
        ),
    ]
