# Generated by Django 5.1.2 on 2025-02-22 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_user_penguins_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penguin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penguin_name', models.CharField(max_length=100)),
                ('svg_direction', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Penguin',
                'verbose_name_plural': 'Penguins',
            },
        ),
        migrations.CreateModel(
            name='PenguinCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collected', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('penguin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.penguin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_penguins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collected Penguin',
                'verbose_name_plural': 'Collected Penguins',
                'unique_together': {('user', 'penguin')},
            },
        ),
    ]
