# Generated by Django 5.1.2 on 2025-02-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_penguin_penguincollected'),
    ]

    operations = [
        migrations.AddField(
            model_name='penguin',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=10),
        ),
    ]
