# Generated by Django 5.1.2 on 2025-02-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_penguin_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='co2_saved',
            field=models.FloatField(default=0),
        ),
    ]
